const routes = [
  ['home','首頁'],['about','關於喬馨'],['journey','探索身體旅程'],['courses','了解課程'],['now-growing','正在發生'],['projects','作品'],['journal','身體之書'],['video','影音'],['contact','聯絡']
];
const A=(route,label,cls='button')=>`<a class="${cls}" href="#/${route}">${label}</a>`;
const pageTitle=(en,zh,lead='')=>`<div class="heading"><span class="eyebrow eyebrow-strong">${en}</span><h1>${zh}</h1>${lead?`<p class="lead">${lead}</p>`:''}</div>`;
const section=(id,en,zh,body)=>`<section class="section" id="${id}"><div class="section-shell"><div class="heading"><span class="eyebrow">${en}</span><h2>${zh}</h2></div>${body}</div></section>`;
const list=items=>`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const homepageJourneys=[{year:'2027',category:'春季｜深度肢體開發旅程',themes:['脊椎活化與正位','核心多面向感知探索'],period:'3月－6月',status:'開放報名'}];
const nav=()=>`<div class="nav-shell"><a class="brand" href="#/home"><img class="brand-mark" src="./assets/header-logo.jpg" alt="" aria-hidden="true" width="420" height="420" /><span class="brand-text"><span class="brand-name">喬馨身體空間</span><small>Chiao Hsin Soma Space</small></span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" aria-label="開啟導覽選單"><svg class="menu-icon menu-icon-open" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18" /></svg><svg class="menu-icon menu-icon-close" viewBox="0 0 24 24" aria-hidden="true" hidden><path d="M5 5l14 14M19 5L5 19" /></svg></button><nav class="nav-links" id="primary-navigation" aria-label="主要導覽">${routes.slice(1).map(([r,n])=>`<a data-route="${r}" href="#/${r}">${n}</a>`).join('')}</nav></div>`;
document.querySelector('#site-header').innerHTML=nav();
document.querySelector('#site-footer').innerHTML=`<div class="footer-shell"><div class="footer-socials" aria-label="社群平台"><a class="social-link" href="https://www.facebook.com/gyrotonic.taiwan" target="_blank" rel="noopener noreferrer" aria-label="Facebook（於新分頁開啟）"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.7 21v-8h2.7l.4-3.1h-3.1V8c0-.9.3-1.6 1.7-1.6h1.8V3.6c-.3 0-1.4-.1-2.6-.1-2.6 0-4.4 1.6-4.4 4.5v1.9H7.3V13h2.9v8h3.5Z"/></svg></a><a class="social-link" href="https://youtube.com/@shijoiuno" target="_blank" rel="noopener noreferrer" aria-label="YouTube（於新分頁開啟）"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 7.2a2.9 2.9 0 0 0-2-2C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.5a2.9 2.9 0 0 0-2 2A30 30 0 0 0 2 12a30 30 0 0 0 .4 4.8 2.9 2.9 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.9 2.9 0 0 0 2-2A30 30 0 0 0 22 12a30 30 0 0 0-.4-4.8ZM10.1 15.1V8.9l5.4 3.1-5.4 3.1Z"/></svg></a><span class="social-link social-link-disabled" role="img" aria-label="Instagram（尚未啟用）" aria-disabled="true"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.1 2h9.8A5.1 5.1 0 0 1 22 7.1v9.8a5.1 5.1 0 0 1-5.1 5.1H7.1A5.1 5.1 0 0 1 2 16.9V7.1A5.1 5.1 0 0 1 7.1 2Zm-.2 2A2.9 2.9 0 0 0 4 6.9v10.2A2.9 2.9 0 0 0 6.9 20h10.2a2.9 2.9 0 0 0 2.9-2.9V6.9A2.9 2.9 0 0 0 17.1 4H6.9ZM12 7.3a4.7 4.7 0 1 1 0 9.4 4.7 4.7 0 0 1 0-9.4Zm0 2a2.7 2.7 0 1 0 0 5.4 2.7 2.7 0 0 0 0-5.4Zm5.9-3.5a1.1 1.1 0 1 1 0 2.2 1.1 1.1 0 0 1 0-2.2Z"/></svg></span><a class="social-link" href="https://vocus.cc/salon/chiaohsin/room/bodymind" target="_blank" rel="noopener noreferrer" aria-label="vocus 方格子（於新分頁開啟）"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.3 4h3.5L12 15.8 16.2 4h3.5L13.5 20h-3L4.3 4Z"/></svg></a></div><div class="footer-divider" aria-hidden="true"></div><div class="footer-info"><p class="copyright">© 2026 喬馨身體空間　Chiao Hsin Soma Space</p><p class="footer-tagline">身體教育・藝術創作・生命表達</p></div></div>`;

document.querySelector('.copyright').innerHTML='<span class="copyright-cn">© 2026 喬馨身體空間</span><span class="copyright-en">Chiao Hsin Soma Space</span>';

const courseCards=`<div class="grid">${[
 ['somatic-awareness','Somatic Awareness','身心覺察','從感受開始，重新建立與身體的連結。'],
 ['soma-development','Soma Development','肢體開發','探索身體能力，發展力量、空間與流動。'],
 ['dance-theatre','Dance Theatre','舞蹈劇場','從表達自己開始，透過舞蹈與創作走向實踐。']
].map(([r,e,t,d],i)=>`<article class="card"><span class="number">0${i+1}</span><span class="en">${e}</span><h3>${t}</h3><p>${d}</p>${A(r,'進入系列')}</article>`).join('')}</div>`;
const journeyEntranceCards=`<div class="journey-entrance-grid"><a class="journey-entrance-card entrance-a" href="#/somatic-awareness" aria-label="從入口 A 身心覺察開始探索"><span class="entrance-marker"><span>入口</span><strong>A</strong></span><img class="journey-entrance-icon" src="./assets/somatic-awareness-icon.png" alt="" aria-hidden="true" width="74" height="78" /><span class="entrance-en">Somatic Awareness</span><h3>身心覺察</h3><p class="journey-entrance-keywords">感知 × 放鬆 × 覺察</p><p class="journey-entrance-copy">從感知身體開始，<br>回到內在的穩定與覺察。</p></a><a class="journey-entrance-card entrance-b" href="#/soma-development" aria-label="從入口 B 肢體開發開始探索"><span class="entrance-marker"><span>入口</span><strong>B</strong></span><img class="journey-entrance-icon" src="./assets/soma-development-icon.png" alt="" aria-hidden="true" width="80" height="79" /><span class="entrance-en">Soma Development</span><h3>肢體開發</h3><p class="journey-entrance-keywords">力量 × 空間 × 流動</p><p class="journey-entrance-copy">透過動作練習，<br>發展全身的穩定與協調能力。</p></a><a class="journey-entrance-card entrance-c" href="#/dance-theatre" aria-label="從入口 C 舞蹈劇場開始探索"><span class="entrance-marker"><span>入口</span><strong>C</strong></span><img class="journey-entrance-icon" src="./assets/dance-theatre-icon.png" alt="" aria-hidden="true" width="88" height="78" /><span class="entrance-en">Dance Theatre</span><h3>舞蹈劇場</h3><p class="journey-entrance-keywords">流動 × 表達</p><p class="journey-entrance-copy">將身體的感知與能力，<br>轉化為創造與表達。</p></a></div>`;
const somaticAwarenessSections={1:`<div class="reading"><p>透過身體動作練習，我們將注意力帶回身體，從感受身體的位置、重量與動作變化開始，發展對身體的覺察能力，學習感受、觀察與理解自己的身體狀態。</p><p class="chapter-insight">在探索的過程中，我們學習重新與身體合作，發展自我調整與平衡的能力。</p></div>`,2:`<div class="reading course-topic-content"><article><h3>身體感知</h3><p>感受身體內在的變化，逐漸發展對身體感受的敏銳度，學習傾聽身體正在傳遞的訊息。</p></article><article><h3>動作覺察</h3><p>透過動作練習，觀察自己的動作與習慣模式，理解身體如何移動，以及如何因應生活環境與日常需求。</p></article><article><h3>身心連結</h3><p>從身體經驗出發，探索身體狀態、情緒與生命經驗之間的關係。</p></article><article><h3>自我調整</h3><p>學習在感受與觀察中，找到適合自己的調整方式，發展身體與生活的平衡。</p></article></div>`,3:`<div class="reading course-topic-content"><article><h3>01｜身心動作觀點與實踐</h3><p>課程重視身體的內在經驗，將身體視為一個活生生、持續變化的有機體。</p><p>透過身心動作觀點與實踐，在練習中觀察身體的感受與變化，重新建立與身體的合作關係。</p></article><article><h3>02｜建立個人的身體感知地圖</h3><p>透過觀察練習前後的身體變化，逐步累積自己的身體經驗，建立個人的身體感知地圖。</p><p>在持續的探索中，學習辨認自己的身體習慣、動作模式、緊繃與放鬆狀態，以及不同情境下的身體需求。</p></article><article><h3>03｜從身體經驗理解自己的模式</h3><p>從身體經驗出發，觀察動作習慣、生活方式與生命經驗如何與當下的身體狀態彼此關聯。</p><p>在覺察這些模式之後，逐漸找到更適合自己的身體使用與調整方式。</p></article><article><h3>04｜多元的身體學習形式</h3><p>除了身體動作練習，系列課程也可能結合身體書寫、影音分享與經驗交流，從不同角度探索身體經驗，深化對自身狀態的理解。</p></article></div>`,4:`<div class="reading"><p>適合：</p>${list(['想發展身體感知與覺察能力的人','想更細緻地感受與理解自己身體狀態的人','想觀察自己的動作習慣，找到更適合自己的身體使用方式的人','對身體覺察、身心連結與身體探索有興趣的人'])}</div>`,5:''};
const somaticAwarenessDirections=`<div class="somatic-awareness-directions"><article class="somatic-awareness-direction"><div class="somatic-awareness-direction-heading"><span class="somatic-awareness-direction-marker" aria-hidden="true"></span><h3>身體感知</h3></div><p>感受身體內在的變化，逐漸發展對身體感受的敏銳度，學習傾聽身體正在傳遞的訊息。</p></article><article class="somatic-awareness-direction"><div class="somatic-awareness-direction-heading"><span class="somatic-awareness-direction-marker" aria-hidden="true"></span><h3>動作覺察</h3></div><p>透過動作練習，觀察自己的動作與習慣模式，理解身體如何移動，以及如何因應生活環境與日常需求。</p></article><article class="somatic-awareness-direction"><div class="somatic-awareness-direction-heading"><span class="somatic-awareness-direction-marker" aria-hidden="true"></span><h3>身心連結</h3></div><p>從身體經驗出發，探索身體狀態、情緒與生命經驗之間的關係。</p></article><article class="somatic-awareness-direction"><div class="somatic-awareness-direction-heading"><span class="somatic-awareness-direction-marker" aria-hidden="true"></span><h3>自我調整</h3></div><p>學習在感受與觀察中，找到適合自己的調整方式，發展身體與生活的平衡。</p></article></div>`;
somaticAwarenessSections[2]=somaticAwarenessDirections;
const somaticAwarenessFeaturesCircleIndex=`<div class="somatic-awareness-notes"><article class="somatic-awareness-note"><div class="somatic-awareness-note-index"><span>01</span></div><h3>身心動作觀點與實踐</h3><div class="somatic-awareness-note-copy"><p>課程重視身體的內在經驗，將身體視為一個活生生、持續變化的有機體。</p><p>透過身心動作觀點與實踐，我們練習重新建立與身體的合作關係，並在過程中觀察身體感受與變化。</p></div></article><article class="somatic-awareness-note"><div class="somatic-awareness-note-index"><span>02</span></div><h3>將注意力帶回身體</h3><div class="somatic-awareness-note-copy"><p>以身體動作練習為核心，透過動作、呼吸與感知練習，重新將注意力帶回當下。</p><p>在練習過程中，逐步發展對自身狀態的覺察能力。</p></div></article><article class="somatic-awareness-note"><div class="somatic-awareness-note-index"><span>03</span></div><h3>建立身體感知地圖</h3><div class="somatic-awareness-note-copy"><p>透過觀察練習前後的身體變化，逐步建立個人的身體經驗資料庫。</p><p>學習辨認：</p><ul><li>身體習慣</li><li>動作模式</li><li>緊繃與放鬆狀態</li><li>個人的身體需求</li></ul></div></article><article class="somatic-awareness-note"><div class="somatic-awareness-note-index"><span>04</span></div><h3>從身體重新認識自己</h3><div class="somatic-awareness-note-copy"><p>從身體經驗出發，探索動作習慣、生活方式與生命經驗如何影響身心狀態。</p><p>並學習重新選擇更適合自己的身體使用方式。</p></div></article></div>`;
const somaticAwarenessFeaturesAbstractMarksPrototype=`<div class="somatic-awareness-feature-marks"><article class="somatic-awareness-feature-mark"><div class="somatic-awareness-feature-header"><svg class="somatic-awareness-abstract-mark" viewBox="0 0 80 80" aria-hidden="true"><path d="M22 18C36 8 58 15 62 31c5 17-7 32-23 34-16 2-27-11-24-26 1-9 2-15 7-21Z"/><circle cx="40" cy="40" r="3.5"/></svg><div><span class="somatic-awareness-feature-index">01</span><h3>身心動作觀點與實踐</h3></div></div><div class="somatic-awareness-feature-copy"><p>課程重視身體的內在經驗，將身體視為一個活生生、持續變化的有機體。</p><p>透過身心動作觀點與實踐，我們練習重新建立與身體的合作關係，並在過程中觀察身體感受與變化。</p></div></article><article class="somatic-awareness-feature-mark"><div class="somatic-awareness-feature-header"><svg class="somatic-awareness-abstract-mark" viewBox="0 0 80 80" aria-hidden="true"><path d="M15 25c11-8 19-9 25-7"/><path d="M15 40c10-4 17-4 24-2"/><path d="M18 55c9 1 16-1 21-6"/><circle cx="43" cy="38" r="3.2"/><path d="M55 24c6 7 8 17 4 27" opacity=".42"/></svg><div><span class="somatic-awareness-feature-index">02</span><h3>將注意力帶回身體</h3></div></div><div class="somatic-awareness-feature-copy"><p>以身體動作練習為核心，透過動作、呼吸與感知練習，重新將注意力帶回當下。</p><p>在練習過程中，逐步發展對自身狀態的覺察能力。</p></div></article><article class="somatic-awareness-feature-mark"><div class="somatic-awareness-feature-header"><svg class="somatic-awareness-abstract-mark" viewBox="0 0 80 80" aria-hidden="true"><path d="M20 25c9 5 13 9 19 14 7 6 12 8 22 12"/><path d="M23 53c7-3 13-5 20-3 6 2 10 4 16 1" opacity=".52"/><circle cx="18" cy="23" r="2.8"/><circle cx="39" cy="39" r="3.4"/><circle cx="64" cy="52" r="2.7"/><circle cx="22" cy="55" r="2.4"/><circle cx="58" cy="26" r="2.5"/></svg><div><span class="somatic-awareness-feature-index">03</span><h3>建立身體感知地圖</h3></div></div><div class="somatic-awareness-feature-copy"><p>透過觀察練習前後的身體變化，逐步建立個人的身體經驗資料庫。</p><p>學習辨認：</p><ul><li>身體習慣</li><li>動作模式</li><li>緊繃與放鬆狀態</li><li>個人的身體需求</li></ul></div></article><article class="somatic-awareness-feature-mark"><div class="somatic-awareness-feature-header"><svg class="somatic-awareness-abstract-mark" viewBox="0 0 80 80" aria-hidden="true"><path d="M23 22c14-9 32 0 34 16 2 15-13 28-28 23-14-5-17-25-6-39Z" opacity=".38"/><path d="M30 17c14 0 25 11 23 25-2 13-16 21-28 14-11-7-11-24 5-39Z"/><path d="M33 30c5-4 11-4 16 0" opacity=".5"/></svg><div><span class="somatic-awareness-feature-index">04</span><h3>從身體重新認識自己</h3></div></div><div class="somatic-awareness-feature-copy"><p>從身體經驗出發，探索動作習慣、生活方式與生命經驗如何影響身心狀態。</p><p>並學習重新選擇更適合自己的身體使用方式。</p></div></article></div>`;
const somaticAwarenessFeatures=`<div class="somatic-awareness-feature-marks-v2"><article class="somatic-awareness-feature-mark-v2 sa-mark-01"><div class="somatic-awareness-feature-header-v2"><svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M22 18C36 8 58 15 62 31c5 17-7 32-23 34-16 2-27-11-24-26 1-9 2-15 7-21Z"/><circle cx="40" cy="40" r="3.5"/></svg><div class="somatic-awareness-feature-heading-v2"><span class="somatic-awareness-feature-index-v2">01</span><h3>身心動作觀點與實踐</h3></div></div><div class="somatic-awareness-feature-copy-v2"><p>課程重視身體的內在經驗，將身體視為一個活生生、持續變化的有機體。</p><p>透過身心動作觀點與實踐，我們練習重新建立與身體的合作關係，並在過程中觀察身體感受與變化。</p></div></article><article class="somatic-awareness-feature-mark-v2 sa-mark-02"><div class="somatic-awareness-feature-header-v2"><svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M13 20c15-12 41-9 49 8 8 16-3 34-19 35-15 1-25-13-20-26 4-10 14-15 22-9"/><circle cx="45" cy="28" r="3.1"/><path d="M16 48c5 9 14 14 24 15" opacity=".42"/></svg><div class="somatic-awareness-feature-heading-v2"><span class="somatic-awareness-feature-index-v2">02</span><h3>將注意力帶回身體</h3></div></div><div class="somatic-awareness-feature-copy-v2"><p>以身體動作練習為核心，透過動作、呼吸與感知練習，重新將注意力帶回當下。</p><p>在練習過程中，逐步發展對自身狀態的覺察能力。</p></div></article><article class="somatic-awareness-feature-mark-v2 sa-mark-03"><div class="somatic-awareness-feature-header-v2"><svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 130 80" aria-hidden="true"><path d="M17 36c10-8 17-12 27-13 12-1 18 9 29 16 11 7 20 6 37-9"/><path d="M20 55c10-5 20-7 30-3 12 5 22 6 34-2" opacity=".5"/><circle cx="16" cy="37" r="2.8"/><circle cx="45" cy="22" r="3.3"/><circle cx="72" cy="39" r="2.8"/><circle cx="108" cy="28" r="2.6"/><circle cx="116" cy="53" r="2.5"/></svg><div class="somatic-awareness-feature-heading-v2"><span class="somatic-awareness-feature-index-v2">03</span><h3>建立身體感知地圖</h3></div></div><div class="somatic-awareness-feature-copy-v2"><p>透過觀察練習前後的身體變化，逐步建立個人的身體經驗資料庫。</p><p>學習辨認：</p><ul class="somatic-awareness-feature-keywords-v2"><li>身體習慣</li><li>動作模式</li><li>緊繃與放鬆狀態</li><li>個人的身體需求</li></ul></div></article><article class="somatic-awareness-feature-mark-v2 sa-mark-04"><div class="somatic-awareness-feature-header-v2"><svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M21 22c13-12 34-4 39 12 5 16-7 31-22 32-15 1-27-13-22-28"/><path d="M17 34c-4-7-2-15 4-20" opacity=".48"/><path d="M49 56c-6 4-13 5-19 2" opacity=".42"/></svg><div class="somatic-awareness-feature-heading-v2"><span class="somatic-awareness-feature-index-v2">04</span><h3>從身體重新認識自己</h3></div></div><div class="somatic-awareness-feature-copy-v2"><p>從身體經驗出發，探索動作習慣、生活方式與生命經驗如何影響身心狀態。</p><p>並學習重新選擇更適合自己的身體使用方式。</p></div></article></div>`;
somaticAwarenessSections[3]=somaticAwarenessFeatures;
const somaticAwarenessFeatures04Updated=somaticAwarenessFeatures.replace('<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M21 22c13-12 34-4 39 12 5 16-7 31-22 32-15 1-27-13-22-28"/><path d="M17 34c-4-7-2-15 4-20" opacity=".48"/><path d="M49 56c-6 4-13 5-19 2" opacity=".42"/></svg>','<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M13 49c10-3 15-13 23-14 8-1 9 10 16 12 8 2 12-8 17-17"/></svg>').replace('<h3>從身體重新認識自己</h3>','<h3>從身體經驗重新認識自己</h3>').replace('<p>並學習重新選擇更適合自己的身體使用方式。</p>','<p>在覺察與理解的過程中，逐漸找到更適合自己的身體使用方式與生活方式。</p>');
somaticAwarenessSections[3]=somaticAwarenessFeatures04Updated;
const somaticAwarenessFeatures04Choice=somaticAwarenessFeatures04Updated.replace('<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M13 49c10-3 15-13 23-14 8-1 9 10 16 12 8 2 12-8 17-17"/></svg>','<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M12 50c12-7 24-11 36-3"/><circle cx="50" cy="48" r="2.6"/><path d="M52 46c7-5 11-12 16-21" opacity=".72"/><path d="M52 51c7 3 12 9 17 16" opacity=".52"/></svg>').replace('<h3>從身體經驗重新認識自己</h3>','<h3>從身體經驗走向生活選擇</h3>');
somaticAwarenessSections[3]=somaticAwarenessFeatures04Choice;
const somaticAwarenessFeatures04Arrows=somaticAwarenessFeatures04Choice.replace('<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M12 50c12-7 24-11 36-3"/><circle cx="50" cy="48" r="2.6"/><path d="M52 46c7-5 11-12 16-21" opacity=".72"/><path d="M52 51c7 3 12 9 17 16" opacity=".52"/></svg>','<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M12 54c9-6 17-8 25-6 5 1 8 4 11 8" opacity=".48"/><path d="M43 56l-5-1 2-4" opacity=".48"/><path d="M21 30c8-8 19-10 28-5 11 6 15 19 11 31-3 9-11 15-21 17"/><path d="M39 73l5-1-1-5"/></svg>');
somaticAwarenessSections[3]=somaticAwarenessFeatures04Arrows;
const somaticAwarenessFeatures04BranchingArrows=somaticAwarenessFeatures04Arrows.replace('<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><path d="M12 54c9-6 17-8 25-6 5 1 8 4 11 8" opacity=".48"/><path d="M43 56l-5-1 2-4" opacity=".48"/><path d="M21 30c8-8 19-10 28-5 11 6 15 19 11 31-3 9-11 15-21 17"/><path d="M39 73l5-1-1-5"/></svg>','<svg class="somatic-awareness-abstract-mark-v2" viewBox="0 0 80 80" aria-hidden="true"><circle cx="14" cy="58" r="2.7"/><path d="M17 57c12-4 24-1 36 4 8 4 15 3 22-1" opacity=".46"/><path d="M70 56l6 4-5 3" opacity=".46"/><path d="M17 57c9-11 19-16 31-14 13 2 24-7 30-22"/><path d="M71 26l7-5-2 8"/></svg>');
somaticAwarenessSections[3]=somaticAwarenessFeatures04BranchingArrows;
const somaticAwarenessAudience=`<div class="somatic-awareness-audience"><p class="somatic-awareness-audience-intro">看看哪些描述，與你現在想探索的方向相近。可複選喔！</p><div class="somatic-awareness-audience-list" role="group" aria-label="適合對象"><button class="somatic-awareness-audience-item somatic-awareness-audience-item-01" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>想重新找回對身體的感受與覺察。</span></button><button class="somatic-awareness-audience-item somatic-awareness-audience-item-02" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>常常感到身體緊繃、疲憊，想更理解自己的身體狀態。</span></button><button class="somatic-awareness-audience-item somatic-awareness-audience-item-03" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>想觀察自己的動作與身體習慣，以及它們如何影響自己的身心狀態。</span></button><button class="somatic-awareness-audience-item somatic-awareness-audience-item-04" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>想透過身體與動作探索，更深入地認識自己。</span></button><button class="somatic-awareness-audience-item somatic-awareness-audience-item-05" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>想在日常生活中，逐漸找到適合自己的調整與平衡方式。</span></button><button class="somatic-awareness-audience-item somatic-awareness-audience-item-06" type="button" aria-pressed="false"><span class="somatic-awareness-audience-marker" aria-hidden="true"></span><span>對自己的身體感到好奇，想看看還有哪些尚未發現的可能。</span></button><p class="somatic-awareness-audience-revelation" aria-live="polite" aria-atomic="true" aria-hidden="true"></p></div></div>`;
somaticAwarenessSections[4]=somaticAwarenessAudience;
somaticAwarenessSections[5]=`<div class="somatic-course-library" aria-label="身心覺察系列課程">
  <a class="somatic-course-card somatic-course-card--available" href="#/somatic-awareness/myofascial-awareness" aria-label="查看課程：肌膜覺察與動作探索">
    <div class="somatic-course-card-media">
      <img src="./assets/myofascial-course-cover.webp" alt="肌膜覺察與動作探索" width="604" height="773" />
    </div>
    <div class="somatic-course-card-body">
      <h3>肌膜覺察與動作探索</h3>
      <p>從身體的連結出發，探索動作如何牽動全身，感受身體不同部位之間的回應。</p>
    </div>
  </a>
  ${Array.from({length:3},(_,index)=>`<article class="somatic-course-card somatic-course-card--placeholder" aria-label="課程 Placeholder ${index+1}">
    <div class="somatic-course-card-media somatic-course-card-placeholder-image" aria-hidden="true"><span>Placeholder</span></div>
    <div class="somatic-course-card-body">
      <h3>課程 Placeholder</h3>
      <p>簡短課程介紹 Placeholder</p>
    </div>
  </article>`).join('')}
</div>`;

const somaDevelopmentSections={1:`<div class="reading"><p>肢體開發系列以身體經驗為核心，透過動作練習，發展身體的感知、穩定與整體協調能力，逐步開展力量、空間與流動。</p><p>課程以脊椎與全身連結為核心，從身體感知與放鬆開始，逐步探索核心穩定、上下肢整合與動作協調，並透過流動性動作與整合練習，將不同的身體能力連結起來。</p><p class="chapter-insight">我們不是單純完成動作，而是在練習的過程中，感受、理解並發展自己的身體。</p></div>`,2:`<div class="reading course-topic-content"><article><span class="en">Awareness &amp; Release</span><h3>身體感知與放鬆</h3><p>從感受身體開始，透過脊椎活化、關節活動與基礎動作練習，探索呼吸、重量、空間，以及身體各部位之間的關係。</p><p>在練習中逐步釋放不必要的張力，感受身體更多的活動空間。</p></article><article><span class="en">Structure &amp; Stability</span><h3>結構與穩定</h3><p>透過核心、上下肢與全身連結練習，探索身體如何在不同姿態與動作中找到支撐、穩定與平衡。</p><p>逐步發展身體中心感、核心穩定與全身協調能力。</p></article><article><span class="en">Flow &amp; Integration</span><h3>流動與整合</h3><p>透過流動性動作、節奏與舞蹈小品等練習，探索身體在空間、速度與動作轉換中的流動。</p><p>將感知、力量與協調逐步連結，發展更完整而具有延展性的身體經驗。</p></article></div>`,3:`<div class="reading course-topic-content"><article><h3>01｜以脊椎為核心的全身連結</h3><p>以脊椎作為身體結構與動作發展的重要軸線，探索核心、上下肢與全身之間的連結，發展整體性的身體使用能力。</p></article><article><h3>02｜從感知到能力發展</h3><p>動作不只是模仿外在形式，而是從身體感受出發，在練習中理解動作，逐步發展穩定、力量、協調與流動能力。</p></article><article><h3>03｜多元身體訓練經驗的整合</h3><p>系列融合禪柔、皮拉提斯、瑜伽、太極與舞蹈等多元身體訓練經驗，但不以單一技術或系統為核心。</p><p>不同方法會依照身體學習的需要重新整理與轉化，成為可以被感受、理解與實踐的動作經驗。</p></article><article><h3>04｜從能力發展走向動作整合</h3><p>透過流動性動作、節奏、舞蹈小品與整合練習，將不同的身體能力連結起來，探索力量、空間與流動之間的轉換。</p></article></div>`,4:`<div class="reading"><p>適合：</p>${list(['想發展身體感知、穩定與協調能力的人','想探索自己的動作習慣與身體使用方式的人','想發展力量、空間與流動等身體能力的人','對身體練習、動作探索與全身整合有興趣的人','想建立持續身體練習經驗的人'])}</div>`,5:''};
const somaDevelopmentExplorations=`<div class="soma-development-explorations"><article class="soma-exploration-card soma-exploration-release"><div class="soma-exploration-motif" aria-hidden="true"><span></span></div><h3>身體感知與放鬆</h3><span class="en">Awareness &amp; Release</span><p class="soma-exploration-description">從感受身體開始，透過脊椎活化、關節活動與基礎動作練習，感受身體更多的活動空間。</p><p class="soma-exploration-keywords">呼吸 · 重量 · 空間 · 身體各部位的關係</p></article><article class="soma-exploration-card soma-exploration-structure"><div class="soma-exploration-motif" aria-hidden="true"><span></span></div><h3>結構與穩定</h3><span class="en">Structure &amp; Stability</span><p class="soma-exploration-description">透過核心、上下肢與全身連結練習，探索身體如何在不同姿態與動作中找到支撐、穩定與平衡。</p><p class="soma-exploration-keywords">身體中心感 · 核心穩定 · 全身協調</p></article><article class="soma-exploration-card soma-exploration-flow"><div class="soma-exploration-motif" aria-hidden="true"><span></span></div><h3>流動與整合</h3><span class="en">Flow &amp; Integration</span><p class="soma-exploration-description">透過流動性動作、節奏與舞蹈小品等練習，探索身體在空間、速度與動作轉換中的流動。</p><p class="soma-exploration-keywords">空間 · 節奏 · 動作轉換 · 流動 · 整合</p></article></div>`;
somaDevelopmentSections[2]=somaDevelopmentExplorations;
/* Soma Development Section 01 — current concise introduction. */
somaDevelopmentSections[1]=`<div class="reading"><p>肢體開發系列以身體經驗為核心，透過動作練習，發展身體的感知、穩定與整體協調能力，探索力量、空間與流動。</p><p class="chapter-insight">我們不是單純完成動作，而是在練習的過程中，感受、理解並發展自己的身體。</p></div>`;
const somaDevelopmentFeatures=`<div class="soma-development-features"><article class="soma-development-feature"><span class="soma-feature-number" aria-hidden="true">01</span><h3>以脊椎為核心的全身連結</h3><div class="soma-feature-copy"><p>以脊椎作為身體結構與動作發展的重要軸線，探索核心、上下肢與全身之間的連結，發展整體性的身體使用能力。</p></div></article><article class="soma-development-feature"><span class="soma-feature-number" aria-hidden="true">02</span><h3>從感知到能力發展</h3><div class="soma-feature-copy"><p>動作不只是模仿外在形式，而是從身體感受出發，在練習中理解動作，逐步發展穩定、力量、協調與流動能力。</p></div></article><article class="soma-development-feature"><span class="soma-feature-number" aria-hidden="true">03</span><h3>多元身體訓練經驗的整合</h3><div class="soma-feature-copy"><p>系列融合禪柔、皮拉提斯、瑜伽、太極與舞蹈等多元身體訓練經驗，但不以單一技術或系統為核心。</p><p>不同方法會依照身體學習的需要重新整理與轉化，成為可以被感受、理解與實踐的動作經驗。</p></div></article><article class="soma-development-feature"><span class="soma-feature-number" aria-hidden="true">04</span><h3>從能力發展走向動作整合</h3><div class="soma-feature-copy"><p>透過流動性動作、節奏、舞蹈小品與整合練習，將不同的身體能力連結起來，探索力量、空間與流動之間的轉換。</p></div></article></div>`;
const somaDevelopmentFeaturesRefined=somaDevelopmentFeatures.replace('<h3>多元身體訓練經驗的整合</h3><div class="soma-feature-copy"><p>系列融合禪柔、皮拉提斯、瑜伽、太極與舞蹈等多元身體訓練經驗，但不以單一技術或系統為核心。</p><p>不同方法會依照身體學習的需要重新整理與轉化，成為可以被感受、理解與實踐的動作經驗。</p></div>','<h3>從身體經驗出發的多元練習</h3><div class="soma-feature-copy"><p>練習取材自禪柔、皮拉提斯、瑜伽、太極與舞蹈等不同身體訓練，從身體經驗與學習需要出發，選擇與調整適合的動作練習。</p></div>').replace('<h3>從能力發展走向動作整合</h3><div class="soma-feature-copy"><p>透過流動性動作、節奏、舞蹈小品與整合練習，將不同的身體能力連結起來，探索力量、空間與流動之間的轉換。</p></div>','<h3>循環探索，持續深入</h3><div class="soma-feature-copy"><p>身體學習不是依照固定順序前進，而是在不同的動作主題中一次次探索。隨著經驗累積，對身體的理解也逐漸深入。</p></div>');
somaDevelopmentSections[3]=somaDevelopmentFeaturesRefined;
const somaDevelopmentAudience=`<div class="soma-development-audience"><p class="soma-audience-intro">看看哪些描述，與現在的你有共鳴。</p><div class="soma-audience-list" role="list"><p class="soma-audience-item" role="listitem"><span class="soma-audience-marker" aria-hidden="true"></span><span>想重新建立身體連結與感受的人</span></p><p class="soma-audience-item" role="listitem"><span class="soma-audience-marker" aria-hidden="true"></span><span>長期處於身體緊繃或慣性使用模式的人</span></p><p class="soma-audience-item" role="listitem"><span class="soma-audience-marker" aria-hidden="true"></span><span>希望發展穩定身體感與動作協調能力的人</span></p><p class="soma-audience-item" role="listitem"><span class="soma-audience-marker" aria-hidden="true"></span><span>對身體練習、動作探索或身心整合有興趣的人</span></p><p class="soma-audience-item" role="listitem"><span class="soma-audience-marker" aria-hidden="true"></span><span>想建立長期、可持續身體練習習慣的人</span></p></div><p class="soma-audience-response">如果其中幾項正是你想探索的方向，<br>肢體開發或許會是一個適合你的入口。</p></div>`;
somaDevelopmentSections[4]=somaDevelopmentAudience;
const somaDevelopmentAudienceInteractive=`<div class="soma-development-audience soma-development-audience-interactive"><p class="soma-audience-intro">看看哪些描述，與現在的你有共鳴。</p><div class="soma-audience-list" role="group" aria-label="適合對象"><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>感受身體</strong><span>想更細緻地感受身體，建立身體感知能力的人</span></span></button><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>舒展放鬆</strong><span>經常感到身體緊繃，想透過動作舒展與放鬆身體的人</span></span></button><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>重塑慣性</strong><span>想覺察動作慣性，並透過練習重塑動作模式的人</span></span></button><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>發展能力</strong><span>希望發展身體的穩定、力量與動作協調能力的人</span></span></button><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>全身連結</strong><span>想發展更均衡的身體使用方式的人</span></span></button><button class="soma-audience-item soma-audience-choice" type="button" aria-pressed="false"><span class="soma-audience-marker" aria-hidden="true"></span><span class="soma-audience-choice-copy"><strong>自主練習</strong><span>想建立長期、可持續身體練習習慣的人</span></span></button></div><div class="soma-audience-figure" aria-live="polite"><div class="soma-audience-figure-frame"><img src="./assets/soma-development-audience-frame-0.png" alt="自然站立的動作人物" width="300" height="390" /></div><p><span class="soma-audience-sprout" aria-hidden="true"></span>點選上方選項，小人會隨著你的選擇一步步向前。</p></div></div>`;
somaDevelopmentSections[4]=somaDevelopmentAudienceInteractive;
const somaDevelopmentAudienceInteractiveRefined=somaDevelopmentAudienceInteractive.replace('<div class="soma-audience-figure" aria-live="polite"><div class="soma-audience-figure-frame"><img src="./assets/soma-development-audience-frame-0.png" alt="自然站立的動作人物" width="300" height="390" /></div><p><span class="soma-audience-sprout" aria-hidden="true"></span>點選上方選項，小人會隨著你的選擇一步步向前。</p></div>','<div class="soma-audience-figure" aria-live="polite"><div class="soma-audience-figure-frame"><img src="./assets/soma-development-audience-frame-0.png" alt="自然站立的動作人物" width="300" height="390" /></div></div>').replaceAll('的人</span></span>','<span class="soma-audience-no-break">的人</span></span></span>').replaceAll('<strong>','<strong><img class="soma-audience-title-sprout" src="./assets/audience-card-sprout.png" alt="" aria-hidden="true" />');
somaDevelopmentSections[4]=somaDevelopmentAudienceInteractiveRefined;
const somaDevelopmentCourseList=`<p class="soma-development-course-list-note">這裡將整理肢體開發系列的課程與學習內容。<br>課程系統建置完成後，將依不同主題持續更新。</p>`;
somaDevelopmentSections[5]=somaDevelopmentCourseList;
const danceTheatreSections={
1:`<div class="reading dance-theatre-intro"><p>舞蹈劇場系列以身體作為創作媒介，透過舞蹈、劇場、意象與生命經驗，將身體經驗轉化為<span class="dance-theatre-keep">表達與創造</span>。</p><p>課程從身心感受出發，在動作中探索情感、意象、節奏與空間，逐步發展身體表達與創造的能力。</p></div>`,
2:`<div class="dance-theatre-directions dance-theatre-directions-two"><article class="dance-theatre-direction dance-theatre-direction-expression"><h3>身體表達</h3><p>從身心感受與動作經驗出發，探索不同的動作品質，以及動作、情感與意象之間如何彼此影響，形成不同的身體表達。</p><p class="dance-theatre-explore-label">探索：</p><div class="dance-theatre-word-cloud" aria-label="身體表達的探索內容"><span>身心狀態與動作品質</span><span>動作詮釋</span><span>情感與意象</span><span>節奏與空間</span></div><figure class="dance-theatre-mobile-direction-dancer dance-theatre-mobile-direction-dancer--glide" aria-hidden="true"><img src="./assets/dance-theatre-dancer-glide.png" alt="" width="205" height="330"></figure></article><figure class="dance-theatre-direction-dancer" aria-hidden="true"><img src="./assets/dance-theatre-dancer-extend.png" alt="" width="185" height="380"></figure><article class="dance-theatre-direction dance-theatre-direction-creation"><h3>創造探索</h3><p>從動作與身心經驗出發，學習運用不同的動作、編舞與劇場元素，發展動作素材、組織身體語彙，逐步形成自己的創作。</p><p class="dance-theatre-explore-label">探索：</p><div class="dance-theatre-word-cloud" aria-label="創造探索的探索內容"><span>動作素材發展</span><span>編舞元素</span><span>劇場元素</span><span>個人經驗的探索與轉化</span></div><figure class="dance-theatre-mobile-direction-dancer dance-theatre-mobile-direction-dancer--grounded" aria-hidden="true"><img src="./assets/dance-theatre-dancer-08-grounded.png" alt="" width="220" height="285"></figure></article></div>`,
3:`<div class="dance-theatre-scenes"><article class="dance-theatre-scene"><span class="dance-theatre-scene-index">01</span><p class="dance-theatre-scene-phrase">身體 <i>→</i> 表達</p><div class="dance-theatre-scene-copy dance-theatre-scene-copy--wide"><h3>身體作為表達媒介</h3><p>舞蹈劇場不只是學習舞蹈技巧，也透過動作與動作品質的體驗，探索如何以身體表達感受、想法與生命經驗。</p></div></article><article class="dance-theatre-scene"><span class="dance-theatre-scene-index">02</span><p class="dance-theatre-scene-phrase">舞蹈 <i>×</i> 劇場 <i>×</i> 意象</p><div class="dance-theatre-scene-copy"><h3>結合舞蹈、劇場與意象</h3><p>結合舞蹈動作、劇場元素與意象探索，從不同角度開展身體語彙與創造方式。</p></div></article><article class="dance-theatre-scene"><span class="dance-theatre-scene-index">03</span><p class="dance-theatre-scene-phrase">經驗 <i>→</i> 創作</p><div class="dance-theatre-scene-copy"><h3>從經驗走向創作</h3><p>從身心感受、想像與生命經驗出發，透過動作探索與編創，逐步發展素材、形成自己的表達與作品。</p></div></article><article class="dance-theatre-scene"><span class="dance-theatre-scene-index">04</span><p class="dance-theatre-scene-phrase">我 <i>↔</i> 空間 <i>↔</i> 他人</p><div class="dance-theatre-scene-copy dance-theatre-scene-copy--wide"><h3>在互動與實踐中開展創作</h3><p>透過練習、作品與分享，讓身體經驗在實踐中逐漸整合，並在與空間、他人及環境的交流中開展更多可能。</p></div></article></div>`,
4:`<div class="dance-theatre-audience"><figure class="dance-theatre-audience-dancer dance-theatre-audience-dancer--left-top" aria-hidden="true"><img src="./assets/dance-theatre-dancer-extend.png" alt="" width="185" height="380"></figure><figure class="dance-theatre-audience-dancer dance-theatre-audience-dancer--right-middle" aria-hidden="true"><img src="./assets/dance-theatre-dancer-glide.png" alt="" width="205" height="330"></figure><figure class="dance-theatre-audience-dancer dance-theatre-audience-dancer--left-bottom" aria-hidden="true"><img src="./assets/dance-theatre-dancer-leap.png" alt="" width="215" height="340"></figure><div class="dance-theatre-audience-list" role="list"><p class="dance-theatre-audience-item" role="listitem"><span aria-hidden="true"></span>想學習舞蹈，感受不同動作所帶來的身心經驗與動作品質的人</p><p class="dance-theatre-audience-item" role="listitem"><span aria-hidden="true"></span>對舞蹈、劇場與身體藝術有興趣的人</p><p class="dance-theatre-audience-item" role="listitem"><span aria-hidden="true"></span>想探索自己的身體語彙與創造方式的人</p><p class="dance-theatre-audience-item" role="listitem"><span aria-hidden="true"></span>想將個人經驗、感受或想像轉化為創作的人</p><p class="dance-theatre-audience-item" role="listitem"><span aria-hidden="true"></span>想透過作品與他人分享、交流的人</p></div><div class="dance-theatre-audience-closing-wrap"><figure class="dance-theatre-audience-closing-dancer dance-theatre-audience-closing-dancer--left" aria-hidden="true"><img src="./assets/dance-theatre-dancer-01-turn.png" alt="" width="205" height="350"></figure><p class="dance-theatre-audience-closing"><span>也許，你只是想看看</span><span>身體還能玩出什麼。</span></p><figure class="dance-theatre-audience-closing-dancer dance-theatre-audience-closing-dancer--right" aria-hidden="true"><img src="./assets/dance-theatre-dancer-leap.png" alt="" width="215" height="340"></figure></div></div>`,
5:''};

const pages={
 home:()=>`<section class="hero"><div class="section-shell hero-layout"><div class="hero-copy"><span class="eyebrow">Soma · Movement · Creation</span><h1>喬馨身體空間</h1><p>透過身體，重新與自己建立連結，<br>活出生命的感覺與創造力。</p>${A('journey','探索身體旅程','button fill')}</div><img class="hero-collage" src="./assets/hero-collage.jpg" alt="喬馨身體空間的身體探索課程紀錄" width="960" height="960" /></div></section>
 ${section('about','About Soma Space','喬馨與這個空間',`<div class="reading"><p>喬馨從身體的探索裡，慢慢認識生命，也逐漸發現：</p><p><strong>身體，不只是讓我們回到自己，也是重新出發的地方。</strong></p><p>喬馨將一路走過的身體探索歷程，以及舞蹈與創作經驗，轉化成一個能與他人相遇、一起練習、感受與創作的空間。</p>${A('about','讀一讀喬馨的身體探索歷程','button fill')}</div>`)}
 ${section('now','Now Growing','正在發生',`<p class="highlight">在這個空間裡，<br>一些練習與相遇正在發生。</p><div class="grid two">${homepageJourneys.map(j=>`<article class="card journey-card"><p class="journey-category">${j.year} ${j.category}</p><div class="journey-themes">${j.themes.map(theme=>`<p class="journey-theme">${theme}</p>`).join('')}</div><p class="journey-meta">${j.period}｜${j.status}</p></article>`).join('')}</div><p class="journey-more">${A('now-growing','查看更多','button fill')}</p>`)}`,
 about:()=>`<section class="section"><div class="section-shell"><div class="heading"><span class="eyebrow eyebrow-strong">About Chiao Hsin</span><h1>關於喬馨</h1></div><nav class="quick-nav"><a href="#dance">從舞蹈開始</a><a href="#injury">重新理解身體</a><a href="#integration">生命整合</a><a href="#creation">重新回到創造</a><a href="#space">空間的形成</a></nav></div></section>
 ${section('dance','01','從舞蹈開始，與身體相遇',`<div class="reading"><p>我與身體的故事，始於舞蹈。</p><p>原先就讀於國立中正大學外文系，一次參與雲門二團的駐校課程後，我開始與舞蹈結緣，並投入現代舞、芭蕾、爵士、民族舞等不同領域的學習。</p><p>比起追求技巧與形式，我更受到舞蹈編創吸引。在編舞的過程中，我不斷深入自己想探問的主題，也探索自己的生命故事。</p><p>舞蹈讓我發現，身體不只是動作的工具，也可以成為說故事的媒介。透過意象、象徵、畫面、情緒與力量，身體能夠表達那些語言無法完整說出的經驗。</p><p>創作，成為我最初理解自己與世界的方式。</p></div>`)}
 ${section('injury','02','從受傷開始，重新理解身體',`<div class="reading"><p>在長期舞蹈訓練的過程中，我反覆受傷，甚至一度連行走都變得困難。身體的限制讓我陷入無助，也迫使我停下來問：</p><p>「為什麼我的身體總是在受傷？」</p><p>這個問題帶領我走進身心學（Somatics）的世界，也正式開啟了我對身體智慧的探索。2010年，我進入台北市立體育學院（今臺北市立大學）舞蹈碩士班，開始接觸身心學的理論與實務。我逐漸發現，身體不只是肌肉、骨骼與動作模式，也承載著我們的生命經驗、情緒、習慣，以及與世界互動的方式。</p><p>我以自身足踝習慣性扭傷為研究起點，透過生命敘說，探究身心動作模式與性格、生命歷程之間的關係。這段探索也讓我逐漸理解：</p><p class="chapter-insight">身體，不只是等待被修復的<span class="no-break">對象</span>，<br>也是理解自己的入口。</p></div>`)}
 ${section('integration','03','從身體探索，到生命整合',`<div class="reading"><p>後來，我再次面對身體帶來的挑戰，也開始尋找更深層的原因。從氣功、食氣到內觀禪修，我透過不同的練習，持續探索身體與內在經驗。</p><p>我當時以為，只要身體先恢復健康，人生的其他問題也會慢慢迎刃而解。因此，多年來，我投入各種練習，希望讓身體恢復平衡與流動。</p><p>然而，在這條路上，我也逐漸發現：</p><p>生命並不一定要等到身體完全恢復，才可以重新開始。</p><p>當我重新回到創作，開始傾聽自己的憤怒、渴望、熱情與恐懼，並重新相信自己的感受時，我慢慢找回了與生命連結的方式。</p><p>我開始理解，生命的成長，不只是修復身體、改善自己，而是：</p><p class="chapter-insight">在每一個當下，重新選擇如何與自己<span class="no-break">相處</span>，<br>如何活出自己的方向。</p></div>`)}
 ${section('creation','04','重新回到創造',`<div class="reading"><p>近年，我重新回到創作。</p><p>透過書寫、舞蹈、作品製作與公開演出，我開始重新找回自己的聲音，也重新相信自己的感受。</p><p class="chapter-insight">創作不只是藝術表達，更是一種整理生命、理解自己，並回應世界的方式。</p><p>在編舞、排練與表演中，身體與生命經驗被轉化，我也在這個過程裡一次次與自己相遇。當自己逐漸變得清晰，我也開始將這份理解帶回生活，重新調整自己的選擇與生活方式，讓生活逐漸長成更貼近自己的樣子。</p><p>創造，也成為我重新實踐生命的道路。</p></div>`)}
 ${section('space','05','喬馨身體空間的形成',`<div class="reading"><p>這些一路走過的經驗，慢慢長成了喬馨身體空間。</p><p>從舞蹈、身心學、教學、創作，到一次次與生命相遇的過程，我逐漸整理出自己對身體的理解，也慢慢建立起屬於自己的工作方式。</p><p>喬馨身體空間，不是一個已經完成的答案。</p><p>它更像是一個持續生長中的空間。</p><p>一個以身體為起點，陪伴人們感受、探索、創造，也陪伴我自己持續探索生命的地方。</p></div>`)}`,
 journey:()=>`<section class="section"><div class="section-shell"><div class="heading"><span class="eyebrow eyebrow-strong">Soma Journey</span><h1>探索身體旅程</h1></div><nav class="quick-nav"><a href="#path">回到自己的入口</a><a href="#soma">Soma</a><a href="#practice">學習方式</a><a href="#map">身體學習地圖</a><a href="#paths">三大探索入口</a></nav></div></section>
 ${section('path','01','身體，是回到自己的入口',`<div class="reading"><p>現代生活裡，我們習慣將注意力放在外在的目標、成果與標準上，卻有時忘記停下來，感受此刻的自己。</p><p>在追求改變的過程中，我們也可能習慣用控制、要求與修正的方式對待身體。</p><p>然而，身體並非只是一個等待被訓練、修正或改善的對象。</p><p class="chapter-insight">它是一個與我們相伴的生命經驗，承載著感受、記憶、習慣與內在狀態。</p><p>透過身體覺察與動作探索，我們學習傾聽身體的訊息，重新建立與自己的連結，發展身體的能力，也在表達與創造中，逐漸找回自己。</p></div>`)}
 ${section('soma','02','我們所說的身體',`<div class="reading"><p>在喬馨身體空間，我們使用 Soma 這個字，來描述我們所理解的身體。</p><p>Soma 指的是：</p><p class="chapter-insight">一個從內在被經驗著、被感受著、活著的身體。</p><p>我們不是站在外面觀看自己的身體，而是從身體裡感受、經驗與生活。</p><p>不同於將身體（body）視為可以從外在觀看、分析或訓練的對象，Soma 關注的是此刻的感受、身體的經驗，以及我們如何活在自己的身體裡。</p><p>因此，身體不只是肌肉、骨骼或姿勢，也是我們感受世界、理解自己，並與生命互動的地方。</p></div>`)}
 ${section('practice','03','學習方式',`<div class="reading"><p>這裡不是追求標準答案的訓練場。</p><p>每個人的身體都有自己的經驗、節奏與可能性。</p><p>無論現在的身體狀態如何，都可以從當下開始，透過感受與探索，重新發現與自己連結的方式。</p><p>身體的學習不只是學會動作與技巧，更是在練習的過程中：</p>${list(['覺察自己的狀態','理解身體的習慣','發展身體的能力','探索身體的表達方式'])}<p class="chapter-insight">身體學習不是一條通往標準答案的道路，而是一段持續感受、探索與創造的旅程。</p><p>在探索身體的旅程中，我們逐漸理解自己的身體，也發現其中蘊含的力量、流動與創造的潛能。</p></div>`)}
 ${section('map','04','身體學習地圖',`<div class="reading"><p class="highlight journey-map-subtitle">三大路徑 × 循環整合 × 持續深化</p><p class="chapter-insight">不同入口，同一個身體的旅程。</p><p>每個入口都可以成為開始的地方。不同的學習路徑並沒有固定順序，而是在持續練習中彼此連結、循環深化。</p><button class="journey-map-trigger" type="button" aria-label="放大檢視身體學習地圖"><img class="journey-map-image" src="./assets/body-learning-map.jpg" alt="喬馨身體空間｜身體學習地圖：三大探索入口與身體學習循環" width="1254" height="1254" /></button></div>`)}
 ${section('paths','05','三大探索入口',`<div class="reading"><p class="chapter-insight">每個人都有一條與身體相遇的道路。</p><p>你可以從適合自己的入口開始，展開一段屬於自己的身體旅程。</p></div>${journeyEntranceCards}`)}`,
 courses:()=>`<section class="section"><div class="section-shell"><div class="heading"><span class="eyebrow eyebrow-strong">Courses &amp; Resources</span><h1>了解課程</h1></div><div class="courses-page-intro">從不同的入口探索身體，也依照自己的需要與興趣，找到適合的學習內容。</div><div class="courses-guide" aria-label="選擇入口，了解主題，探索課程與學習資源"><span>選擇入口</span><span class="courses-guide-arrow" aria-hidden="true">→</span><span>了解主題</span><span class="courses-guide-arrow" aria-hidden="true">→</span><span class="courses-guide-final">探索課程與學習資源</span></div>${journeyEntranceCards}</div></section>`,
 'somatic-awareness':()=>courseTopicPage('Somatic Awareness','身心覺察','從感知身體開始，回到內在的穩定與覺察。','somatic-awareness-page-content-v0.1.md',somaticAwarenessSections),
 'somatic-awareness/myofascial-awareness':()=>`<section class="myofascial-magazine-route" aria-label="肌膜覺察與動作探索"><iframe src="./myofascial-magazine/index.html" title="肌膜覺察與動作探索" loading="eager"></iframe></section>`,
 'somatic-awareness/spine-awareness':()=>`<section class="spine-magazine-route" aria-label="脊椎感知與身體排列"><iframe src="./spine-magazine/index.html" title="脊椎感知與身體排列" loading="eager"></iframe></section>`,
 'soma-development':()=>courseTopicPage('Soma Development','肢體開發','透過動作練習，發展全身的穩定與協調能力。','soma-development-page-content-v0.1.md',somaDevelopmentSections),
 'dance-theatre':()=>courseTopicPage('Dance Theatre','舞蹈劇場','將身體的感知與能力，轉化為創造與表達。','dance-theatre-page-content-v0.1.md',danceTheatreSections),
 'now-growing':()=>`<section class="section now-growing-page"><div class="section-shell"><div class="heading"><span class="eyebrow eyebrow-strong">Now Growing</span><h1>正在發生</h1><p class="lead">正在展開的身體旅程、活動與創作實踐。</p></div><nav class="quick-nav now-growing-inpage-nav" aria-label="頁面快速導覽"><a href="#start">開始你的身體旅程</a><a href="#events">旅程與活動</a><a href="#past">Past Growing</a></nav></div></section>${section('start','01','開始你的身體旅程',`<div class="reading"><p>在這個空間裡，每個季節有不同的身體旅程展開。你可以依照自己的生命節奏，選擇適合自己的旅程。</p>${list(['春秋｜深度肢體開發旅程','全年｜一日身心覺察工作坊','夏季｜舞蹈劇場探索工作坊','年末｜作品與創造呈現'])}</div>`)}${section('events','02','旅程與活動',`<div class="grid two"><article class="card"><span class="en">2027 春季｜開放報名</span><h3>深度肢體開發旅程</h3><p>脊椎活化與正位 × 核心多面向感知探索<br>3月－6月</p></article><article class="card"><span class="en">全年｜開放報名</span><h3>一日身心覺察工作坊</h3><p>身體覺察、狀態與自我連結探索</p></article></div>`)}${section('past','03','歷年旅程紀錄',`<p class="reading">曾經發生的身體旅程、活動與創作，會慢慢收錄在這裡。</p>`)}`,
 journal:()=>externalPage('Soma Journal','身體之書','從身體的探索裡，慢慢留下些什麼。','有一些身體裡的感受，會慢慢變成文字。這裡記錄喬馨對身體、生命與創作的觀察，也分享身體練習時的探索與發現。','閱讀身體之書','https://vocus.cc/salon/chiaohsin/room/bodymind','更多文章與身體探索內容，目前發表於方格子。'),
 video:()=>externalPage('Video','影音','身體 × 聲音 × 影像','身體練習、短片與創作影像，目前主要發表於 YouTube。','前往 YouTube 頻道','https://youtube.com/@shijoiuno',''),
 projects:()=>`<section class="section works-page" id="projects"><div class="section-shell"><div class="heading works-page-heading"><span class="eyebrow eyebrow-strong">Works</span><h1>作品</h1></div><div class="works-page-intro"><p>這裡收錄喬馨身體空間的舞蹈編創小品、舞蹈劇場作品與舞蹈影像創作。</p><p>從舞台上的身體創作，到影像中的再次轉化，記錄作品從發想到呈現，以及在不同媒介中持續發展的軌跡。</p></div><div class="works-archive" aria-label="作品列表"><p class="works-archive-empty">作品整理中，將陸續收錄。</p></div></div></section>`,
 contact:()=>`<section class="section contact-page"><div class="section-shell"><div class="contact-page-layout"><div class="contact-page-copy"><div class="heading"><span class="eyebrow eyebrow-strong">Contact</span><h1>聯絡</h1></div><div class="contact-page-content"><p class="contact-page-intro">如果你對課程或工作坊有任何問題，<br class="contact-desktop-break">或是合作、講座、交流與其他相關邀請，歡迎與喬馨聯絡。</p><div class="contact-page-actions"><a class="button fill" href="mailto:shijoiuno@gmail.com">寫信給喬馨</a><a class="button fill contact-line-link" href="https://lin.ee/VWvZiEww" target="_blank" rel="noopener noreferrer">加入 LINE</a></div></div></div><figure class="contact-page-illustration" aria-hidden="true"><img src="./assets/contact-letter-illustration.png" alt="" width="1200" height="850"></figure></div></div></section>`
};
function courseTopicPage(en,zh,lead,_legacySourceKey,sectionOverrides={}){const body=index=>sectionOverrides[index]||'',nav=`<nav class="quick-nav course-topic-inpage-nav" aria-label="頁面快速導覽"><a href="#course-intro">系列介紹</a><a href="#course-directions">探索方向</a><a href="#course-features">課程特色</a><a href="#course-audience">適合對象</a><a href="#course-list">課程列表</a></nav>`,header=`<div class="heading"><span class="eyebrow eyebrow-strong">${en}</span><h1>${zh}</h1><p class="lead">${lead}</p></div>`;return `<section class="section course-topic-page"><div class="section-shell">${header}${nav}</div></section>${section('course-intro','01','系列介紹',body(1))}${section('course-directions','02','探索方向',body(2))}${section('course-features','03','課程特色',body(3))}${section('course-audience','04','適合對象',body(4))}${section('course-list','05','課程列表',body(5))}`}
function externalPage(en,zh,headline,copy,label,url,note){return `<section class="section"><div class="section-shell">${pageTitle(en,zh)}<div class="external"><div><p class="highlight">${headline}</p><p>${copy}</p>${note?`<p>${note}</p>`:''}</div><a class="button fill" href="${url}" target="_blank" rel="noreferrer">${label}</a></div></div></section>`}
const courseTopicPageBase=courseTopicPage;
courseTopicPage=(en,zh,lead,sourceKey,sectionOverrides={})=>{const page=courseTopicPageBase(en,zh,lead,sourceKey,sectionOverrides);if(en==='Soma Development')return page.replace('<h1>肢體開發</h1>','<div class="soma-development-title-mark"><h1>肢體開發</h1><img src="./assets/soma-development-icon.png" alt="" aria-hidden="true" width="80" height="79" /></div>');if(en==='Somatic Awareness')return page.replace('<h1>身心覺察</h1>','<div class="somatic-awareness-title-mark"><h1>身心覺察</h1><img src="./assets/somatic-awareness-icon.png" alt="" aria-hidden="true" width="74" height="78" /></div>');if(en==='Dance Theatre'){let dancePage=page.replace('<h1>舞蹈劇場</h1>','<div class="dance-theatre-title-mark"><h1>舞蹈劇場</h1><img src="./assets/dance-theatre-icon.png" alt="" aria-hidden="true" width="88" height="78" /></div>');const marks=[['系列介紹','intro','dance-theatre-dancer-extend.png',185,380],['探索方向','directions','dance-theatre-dancer-04-backbend.png',165,300],['課程特色','features','dance-theatre-dancer-01-turn.png',205,350],['適合對象','audience','dance-theatre-dancer-05-step.png',210,315],['課程列表','list','dance-theatre-dancer-06-turn.png',170,315]];marks.forEach(([label,key,asset,width,height])=>{dancePage=dancePage.replace('<h2>'+label+'</h2>','<div class="dance-theatre-section-title-mark dance-theatre-section-title-mark--'+key+'"><h2>'+label+'</h2><img src="./assets/'+asset+'" alt="" aria-hidden="true" width="'+width+'" height="'+height+'" /></div>')});return dancePage}return page};
const courseTopicPageWithSeriesMark=courseTopicPage;
const courseExploreDestinations={
  'Somatic Awareness':{course:'somatic',label:'肢體開發',href:'#/soma-development'},
  'Soma Development':{course:'soma',label:'舞蹈劇場',href:'#/dance-theatre'},
  'Dance Theatre':{course:'dance',label:'身心覺察',href:'#/somatic-awareness'}
};
function courseExploreFooter(en){const destination=courseExploreDestinations[en];if(!destination)return '';return `<nav class="course-explore-footer" aria-label="課程探索導航"><a href="#/courses">← 回到探索入口</a><span aria-hidden="true">｜</span><a href="${destination.href}">${destination.label} →</a></nav>`}
courseTopicPage=(en,zh,lead,sourceKey,sectionOverrides={})=>`${courseTopicPageWithSeriesMark(en,zh,lead,sourceKey,sectionOverrides)}${courseExploreFooter(en)}`;
let mapLightbox=null,mapLightboxOpener=null;
function closeMapLightbox(){if(!mapLightbox)return;const closingLightbox=mapLightbox;mapLightbox=null;document.body.classList.remove('image-lightbox-open');closingLightbox.remove();mapLightboxOpener?.focus();mapLightboxOpener=null}
function openMapLightbox(trigger){const sourceImage=trigger.querySelector('.journey-map-image');if(!sourceImage)return;closeMapLightbox();mapLightboxOpener=trigger;const lightbox=document.createElement('div'),stage=document.createElement('div'),controls=document.createElement('div'),zoomOut=document.createElement('button'),zoomIn=document.createElement('button'),fitButton=document.createElement('button'),closeButton=document.createElement('button'),image=document.createElement('img'),zoomLevels=[1,1.75,2.5],pointers=new Map();let scale=1,panX=0,panY=0,dragStart=null,pinchStart=null,tapTarget=null,moved=false;
lightbox.className='image-lightbox';lightbox.setAttribute('role','dialog');lightbox.setAttribute('aria-modal','true');lightbox.setAttribute('aria-label','身體學習地圖放大檢視');stage.className='image-lightbox-stage';stage.setAttribute('aria-label','可放大及拖曳的身體學習地圖');controls.className='image-lightbox-controls';[[zoomOut,'−','縮小地圖'],[zoomIn,'+','放大地圖'],[fitButton,'Fit','回到完整地圖'],[closeButton,'×','關閉放大檢視']].forEach(([button,label,aria])=>{button.type='button';button.textContent=label;button.setAttribute('aria-label',aria);controls.append(button)});closeButton.className='image-lightbox-close';image.className='image-lightbox-image';image.src=sourceImage.currentSrc||sourceImage.src;image.alt=sourceImage.alt;image.width=sourceImage.naturalWidth||1254;image.height=sourceImage.naturalHeight||1254;
const constrainPan=()=>{const stageBox=stage.getBoundingClientRect(),imageWidth=image.offsetWidth*scale,imageHeight=image.offsetHeight*scale,maxX=Math.max(0,(imageWidth-stageBox.width)/2),maxY=Math.max(0,(imageHeight-stageBox.height)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY))};const updateViewer=()=>{constrainPan();image.style.transform=`translate(${panX}px,${panY}px) scale(${scale})`;stage.classList.toggle('is-zoomed',scale>1);zoomOut.disabled=scale===1;zoomIn.disabled=scale===zoomLevels.at(-1)};const setScale=next=>{scale=Math.max(zoomLevels[0],Math.min(zoomLevels.at(-1),next));if(scale===1){panX=0;panY=0}updateViewer()};const zoomStep=direction=>{const levels=direction>0?zoomLevels:[...zoomLevels].reverse(),next=levels.find(level=>direction>0?level>scale:level<scale);setScale(next??(direction>0?zoomLevels.at(-1):zoomLevels[0]))};const resetViewer=()=>setScale(1);
zoomIn.addEventListener('click',()=>zoomStep(1));zoomOut.addEventListener('click',()=>zoomStep(-1));fitButton.addEventListener('click',resetViewer);closeButton.addEventListener('click',closeMapLightbox);controls.addEventListener('pointerdown',event=>event.stopPropagation());lightbox.addEventListener('click',event=>{if(event.target===lightbox)closeMapLightbox()});stage.addEventListener('click',event=>{if(event.target===stage&&!moved)closeMapLightbox()});
stage.addEventListener('pointerdown',event=>{pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});stage.setPointerCapture?.(event.pointerId);tapTarget=event.target;moved=false;if(pointers.size===2){const points=[...pointers.values()];pinchStart={distance:Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y),scale};dragStart=null}else if(scale>1){dragStart={x:event.clientX,y:event.clientY,panX,panY}}});stage.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2&&pinchStart){const points=[...pointers.values()],distance=Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y);if(Math.abs(distance-pinchStart.distance)>3)moved=true;setScale(pinchStart.scale*(distance/pinchStart.distance))}else if(dragStart){const deltaX=event.clientX-dragStart.x,deltaY=event.clientY-dragStart.y;if(Math.hypot(deltaX,deltaY)>3)moved=true;panX=dragStart.panX+deltaX;panY=dragStart.panY+deltaY;updateViewer()}});stage.addEventListener('pointerup',event=>{const startPoint=pointers.get(event.pointerId),wasTap=startPoint&&!moved&&pointers.size===1;pointers.delete(event.pointerId);if(pointers.size<2)pinchStart=null;dragStart=null;if(wasTap&&tapTarget===image&&event.pointerType==='mouse'){const next=zoomLevels.find(level=>level>scale)??1;setScale(next)}tapTarget=null});stage.addEventListener('pointercancel',event=>{pointers.delete(event.pointerId);dragStart=null;pinchStart=null;tapTarget=null});image.addEventListener('load',updateViewer,{once:true});stage.append(image);lightbox.append(stage,controls);document.body.append(lightbox);document.body.classList.add('image-lightbox-open');mapLightbox=lightbox;closeButton.focus()}
function setNavOpen(isOpen){const menu=document.querySelector('.nav-links'),button=document.querySelector('.nav-toggle');menu.classList.toggle('open',isOpen);button.setAttribute('aria-expanded',String(isOpen));button.setAttribute('aria-label',isOpen?'關閉導覽選單':'開啟導覽選單');button.querySelector('.menu-icon-open').toggleAttribute('hidden',isOpen);button.querySelector('.menu-icon-close').toggleAttribute('hidden',!isOpen)}
let somaticAudienceBoundaryObserver=null,somaticAudienceSectionActive=false;
function syncSomaticAudienceBoundary(){const revelation=document.querySelector('#course-audience .somatic-awareness-audience-revelation');if(!revelation||!matchMedia('(max-width:760px)').matches)return;revelation.classList.toggle('is-mobile-section-active',somaticAudienceSectionActive&&revelation.classList.contains('is-visible'))}
function setupSomaticAudienceBoundary(){somaticAudienceBoundaryObserver?.disconnect();somaticAudienceBoundaryObserver=null;somaticAudienceSectionActive=false;const section=document.querySelector('#course-audience'),revelation=section?.querySelector('.somatic-awareness-audience-revelation');if(!section||!revelation||!window.IntersectionObserver)return;somaticAudienceBoundaryObserver=new IntersectionObserver(([entry])=>{const wasActive=somaticAudienceSectionActive;somaticAudienceSectionActive=entry.isIntersecting;if(somaticAudienceSectionActive&&!wasActive&&revelation.classList.contains('is-visible'))revelation.dataset.mobileTransition='return';syncSomaticAudienceBoundary()},{root:null,rootMargin:'-30% 0px -30% 0px',threshold:0});somaticAudienceBoundaryObserver.observe(section)}
let somaAudienceFigureBoundaryObserver=null;
function setupSomaAudienceFigureBoundary(){somaAudienceFigureBoundaryObserver?.disconnect();somaAudienceFigureBoundaryObserver=null;const section=document.querySelector('#course-audience'),figure=section?.querySelector('.soma-development-audience-interactive .soma-audience-figure');if(!section||!figure||!window.IntersectionObserver)return;somaAudienceFigureBoundaryObserver=new IntersectionObserver(([entry])=>{figure.classList.toggle('is-mobile-section-active',entry.isIntersecting)},{root:null,rootMargin:'-18% 0px -22% 0px',threshold:0});somaAudienceFigureBoundaryObserver.observe(section)}
const desktopLongReadRoutes=new Set(['about','journey','somatic-awareness','soma-development','dance-theatre']);
function render(){closeMapLightbox();const route=(location.hash.match(/^#\/([^?]+)/)||[, 'home'])[1];const view=pages[route]||pages.home,isMyofascialMagazine=route==='somatic-awareness/myofascial-awareness',isSpineMagazine=route==='somatic-awareness/spine-awareness',isCourseMagazine=isMyofascialMagazine||isSpineMagazine,isDesktopLongRead=desktopLongReadRoutes.has(route);document.body.classList.toggle('is-myofascial-magazine-route',isMyofascialMagazine);document.body.classList.toggle('is-course-magazine-route',isCourseMagazine);document.body.classList.toggle('is-desktop-long-read-route',isDesktopLongRead);document.body.classList.remove('is-site-header-collapsed');document.querySelector('#main').innerHTML=view();document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));setNavOpen(false);window.scrollTo(0,0);resetDesktopHeaderScrollState();const routeTitle=isMyofascialMagazine?'肌膜覺察與動作探索':isSpineMagazine?'脊椎感知與身體排列':route==='home'?'喬馨身體空間':(routes.find(x=>x[0]===route)||['','喬馨身體空間'])[1];document.title=`${routeTitle}｜喬馨身體空間`}
function scrollToRequestedSection(){const query=location.hash.split('?')[1];if(!query)return;const sectionId=new URLSearchParams(query).get('section');if(!sectionId)return;requestAnimationFrame(()=>document.getElementById(sectionId)?.scrollIntoView({block:'start'}))}
function setupInPageNav(){const main=document.querySelector('#main'),intro=main.firstElementChild,nav=intro?.querySelector('.quick-nav');if(!nav)return;const isAbout=nav.querySelector('a[href="#dance"]'),isJourney=nav.querySelector('a[href="#path"]'),isCourse=nav.classList.contains('course-topic-inpage-nav'),isNowGrowing=nav.classList.contains('now-growing-inpage-nav'),variant=isAbout?'about-inpage-nav':isJourney?'journey-inpage-nav':isCourse?'course-topic-inpage-nav':isNowGrowing?'now-growing-inpage-nav':'';if(!variant)return;nav.classList.add('inpage-nav',variant);[...nav.querySelectorAll('a')].forEach((link,index)=>{const name=link.textContent;link.innerHTML=`<span class="chapter-index">${String(index+1).padStart(2,'0')}</span><span class="chapter-name">${name}</span>`});intro.before(nav)}
const desktopHeaderMedia=matchMedia('(min-width:901px)');
let desktopHeaderLastY=window.scrollY,desktopHeaderDirection=0,desktopHeaderDistance=0;
function resetDesktopHeaderScrollState(){desktopHeaderLastY=window.scrollY;desktopHeaderDirection=0;desktopHeaderDistance=0}
function syncDesktopHeaderOnScroll(){const body=document.body,currentY=window.scrollY;if(!desktopHeaderMedia.matches||!body.classList.contains('is-desktop-long-read-route')){body.classList.remove('is-site-header-collapsed');resetDesktopHeaderScrollState();return}const delta=currentY-desktopHeaderLastY;desktopHeaderLastY=currentY;if(currentY<=64){body.classList.remove('is-site-header-collapsed');desktopHeaderDirection=0;desktopHeaderDistance=0;return}if(Math.abs(delta)<2)return;const direction=delta>0?1:-1;if(direction!==desktopHeaderDirection){desktopHeaderDirection=direction;desktopHeaderDistance=0}desktopHeaderDistance+=Math.abs(delta);if(direction>0&&currentY>180&&desktopHeaderDistance>=28){body.classList.add('is-site-header-collapsed');desktopHeaderDistance=0}else if(direction<0&&desktopHeaderDistance>=48){body.classList.remove('is-site-header-collapsed');desktopHeaderDistance=0}}
window.addEventListener('scroll',syncDesktopHeaderOnScroll,{passive:true});
desktopHeaderMedia.addEventListener?.('change',syncDesktopHeaderOnScroll);
document.addEventListener('click',e=>{const link=e.target.closest('.inpage-nav a[href^="#"]');if(!link)return;const target=document.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})});
document.addEventListener('click',event=>{const trigger=event.target.closest('.journey-map-trigger');if(trigger)openMapLightbox(trigger)});
document.addEventListener('click',event=>{const item=event.target.closest('.somatic-awareness-audience-item');if(!item)return;const selected=item.getAttribute('aria-pressed')==='true';item.setAttribute('aria-pressed',String(!selected));const audience=item.closest('.somatic-awareness-audience'),revelation=audience?.querySelector('.somatic-awareness-audience-revelation');if(!revelation)return;const selectedCount=audience.querySelectorAll('.somatic-awareness-audience-item[aria-pressed="true"]').length,messages={1:'嗯……有一個方向，好像被你認出來了。',2:'看來，你對自己的身體真的有點好奇。',3:'三個了。看來，身體真的有些話想跟你說。',4:'身心覺察，也許會是一個適合你的探索入口。',5:'你想探索的方向，正在慢慢變得清晰。',6:'讓身體引領你，走出屬於你的步伐。'}[selectedCount];revelation.classList.remove('is-visible');revelation.dataset.count=String(selectedCount);if(!messages){revelation.setAttribute('aria-hidden','true');revelation.textContent='';syncSomaticAudienceBoundary();return}revelation.textContent=messages;revelation.dataset.mobileTransition='selection';revelation.setAttribute('aria-hidden','false');requestAnimationFrame(()=>{if(revelation.dataset.count===String(selectedCount)){revelation.classList.add('is-visible');syncSomaticAudienceBoundary()}})});
document.addEventListener('click',event=>{const item=event.target.closest('.soma-audience-choice');if(!item)return;const selected=item.getAttribute('aria-pressed')==='true';item.setAttribute('aria-pressed',String(!selected));const audience=item.closest('.soma-development-audience-interactive'),figure=audience?.querySelector('.soma-audience-figure'),image=figure?.querySelector('img');if(!image)return;const count=audience.querySelectorAll('.soma-audience-choice[aria-pressed="true"]').length,labels=['自然站立的動作人物','啟動向前的動作人物','左腳跨步的動作人物','重心轉移的動作人物','右腳跨步的動作人物','伸展開展的動作人物','跳躍展開的動作人物'];image.src=`./assets/soma-development-audience-frame-${count}.png`;image.alt=labels[count];figure.dataset.frame=String(count)});
document.addEventListener('keydown',event=>{const item=event.target.closest?.('.somatic-awareness-audience-item');if(!item||!['Enter',' '].includes(event.key))return;event.preventDefault();item.click()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMapLightbox()});
document.querySelector('.nav-toggle').addEventListener('click',e=>setNavOpen(!document.querySelector('.nav-links').classList.contains('open')));
window.addEventListener('hashchange',()=>{render();setupInPageNav();setupSomaticAudienceBoundary();setupSomaAudienceFigureBoundary();scrollToRequestedSection()});render();setupInPageNav();setupSomaticAudienceBoundary();setupSomaAudienceFigureBoundary();scrollToRequestedSection();

document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link||link.getAttribute('href').startsWith('#/'))return;const id=link.getAttribute('href').slice(1),target=document.getElementById(id);if(target){event.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}});
