const routes = [
  ['home','首頁'],['about','關於喬馨'],['journey','探索身體旅程'],['courses','課程'],['now-growing','正在發生'],['projects','作品'],['journal','身體之書'],['video','影音'],['contact','聯絡']
];
const A=(route,label,cls='button')=>`<a class="${cls}" href="#/${route}">${label}</a>`;
const pageTitle=(en,zh,lead='')=>`<div class="heading"><span class="eyebrow">${en}</span><h1>${zh}</h1>${lead?`<p class="lead">${lead}</p>`:''}</div>`;
const section=(id,en,zh,body)=>`<section class="section" id="${id}"><div class="section-shell"><div class="heading"><span class="eyebrow">${en}</span><h2>${zh}</h2></div>${body}</div></section>`;
const list=items=>`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const homepageJourneys=[{year:'2027',category:'春季｜深度肢體開發旅程',themes:['脊椎活化與正位','核心多面向感知探索'],period:'3月－6月',status:'開放報名',detailUrl:'#/now-growing/2027-spring-soma-development'}];
const nav=()=>`<div class="nav-shell"><a class="brand" href="#/home"><img class="brand-mark" src="./assets/header-logo.jpg" alt="" aria-hidden="true" width="420" height="420" /><span class="brand-text"><span class="brand-name">喬馨身體空間</span><small>Chiao Hsin Soma Space</small></span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" aria-label="開啟導覽選單"><svg class="menu-icon menu-icon-open" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18" /></svg><svg class="menu-icon menu-icon-close" viewBox="0 0 24 24" aria-hidden="true" hidden><path d="M5 5l14 14M19 5L5 19" /></svg></button><nav class="nav-links" id="primary-navigation" aria-label="主要導覽">${routes.slice(1).map(([r,n])=>`<a data-route="${r}" href="#/${r}">${n}</a>`).join('')}</nav></div>`;
document.querySelector('#site-header').innerHTML=nav();
document.querySelector('#site-footer').innerHTML=`<div class="footer-shell"><div class="footer-brand">喬馨身體空間<p>身體教育・藝術創作・生命表達</p></div><div class="socials"><a href="#/contact">LINE</a><a href="#/contact">Instagram</a><a href="#/contact">Facebook</a><a href="#/contact">Threads</a><a href="https://youtube.com/@shijoiuno" target="_blank" rel="noreferrer">YouTube</a></div><p class="copyright">© 2026 喬馨身體空間　Chiao Hsin Soma Space</p></div>`;

const courseCards=`<div class="grid">${[
 ['somatic-awareness','Somatic Awareness','身心覺察','從感受開始，重新建立與身體的連結。'],
 ['soma-development','Soma Development','肢體開發','探索身體能力，發展力量、空間與流動。'],
 ['dance-theatre','Dance Theatre','舞蹈劇場','從表達自己開始，透過舞蹈與創作走向實踐。']
].map(([r,e,t,d],i)=>`<article class="card"><span class="number">0${i+1}</span><span class="en">${e}</span><h3>${t}</h3><p>${d}</p>${A(r,'進入系列')}</article>`).join('')}</div>`;

const pages={
 home:()=>`<section class="hero"><div class="section-shell hero-layout"><div class="hero-copy"><span class="eyebrow">Soma · Movement · Creation</span><h1>喬馨身體空間</h1><p>透過身體，重新與自己建立連結，<br>活出生命的感覺與創造力。</p>${A('journey','探索身體旅程','button fill')}</div><img class="hero-collage" src="./assets/hero-collage.jpg" alt="喬馨身體空間的身體探索課程紀錄" width="960" height="960" /></div></section>
 ${section('about','About Soma Space','喬馨與這個空間',`<div class="reading"><p>喬馨從身體的探索裡，慢慢認識生命，也逐漸發現：</p><p><strong>身體，不只是讓我們回到自己，也是重新出發的地方。</strong></p><p>喬馨將一路走過的身體探索歷程，以及舞蹈與創作經驗，轉化成一個能與他人相遇、一起練習、感受與創作的空間。</p>${A('about','讀一讀喬馨的身體探索歷程','button fill')}</div>`)}
 ${section('now','Now Growing','正在發生',`<p class="highlight">在這個空間裡，<br>一些練習與相遇正在發生。</p><div class="grid two">${homepageJourneys.map(j=>`<a class="card journey-card" href="${j.detailUrl}" aria-label="查看 ${j.year} ${j.category}"><p class="journey-category">${j.year} ${j.category}</p><div class="journey-themes">${j.themes.map(theme=>`<p class="journey-theme">${theme}</p>`).join('')}</div><p class="journey-meta">${j.period}｜${j.status}</p></a>`).join('')}</div><p class="journey-more">${A('now-growing','查看更多','button fill')}</p>`)}`,
 about:()=>`<section class="section"><div class="section-shell">${pageTitle('About Chiao Hsin','關於喬馨','本頁記錄喬馨與身體相遇、探索與創作的生命歷程。')}<nav class="quick-nav"><a href="#dance">從舞蹈開始</a><a href="#injury">重新理解身體</a><a href="#integration">生命整合</a><a href="#creation">重新回到創造</a><a href="#space">空間的形成</a></nav></div></section>
 ${section('dance','01','從舞蹈開始，與身體相遇',`<div class="reading"><p>我與身體的故事，始於舞蹈。</p><p>原先就讀於國立中正大學外文系，一次參與雲門二團的駐校課程後，我開始與舞蹈結緣，並投入現代舞、芭蕾、爵士、民族舞等不同領域的學習。</p><p>比起追求技巧與形式，我更受到舞蹈編創吸引。舞蹈讓我發現，身體不只是動作的工具，也可以成為說故事的媒介；創作，成為我最初理解自己與世界的方式。</p></div>`)}
 ${section('injury','02','從受傷開始，重新理解身體',`<div class="reading"><p>在長期舞蹈訓練的過程中，我經歷了反覆受傷，開始問：「為什麼我的身體總是在受傷？」</p><p>這個問題帶領我走進身心學（Somatics）的世界。後來我進入台北市立體育學院舞蹈研究所，從自身長期足踝習慣性扭傷出發，探索身體模式、性格與生命歷程之間的關係。</p><p>身體，不只是需要被修正的對象，而是理解自己的入口。</p></div>`)}
 ${section('integration','03','從身體探索，到生命整合',`<div class="reading"><p>從氣功、食氣實驗、內觀禪修，到後來重新回到創作，我持續探索身體、意識、情緒與生命選擇之間的關係。</p><p>生命並不一定要等到身體完全恢復，才可以重新開始。當我重新傾聽自己的感受，也慢慢找回與生命連結的方式。</p></div>`)}
 ${section('creation','04','重新回到創造',`<div class="reading"><p>近年，我透過書寫、舞蹈、作品製作與公開演出，重新找回自己的聲音，也重新相信自己的感受。</p><p>創作不只是藝術表達，更是一種整理生命、理解自己，並回應世界的方式。</p></div>`)}
 ${section('space','05','喬馨身體空間的形成',`<div class="reading"><p>從舞蹈、身心學、教學、創作，到一次次與生命相遇的過程，我逐漸整理出自己對身體的理解，也慢慢建立起屬於自己的工作方式。</p><p>喬馨身體空間不是一個已經完成的答案，而是一個持續生長中的空間：以身體為起點，陪伴人們感受、探索、創造，也陪伴我自己持續探索生命。</p></div>`)}`,
 journey:()=>`<section class="section"><div class="section-shell">${pageTitle('Soma Journey','探索身體旅程')}<nav class="quick-nav"><a href="#path">回到自己的入口</a><a href="#soma">Soma</a><a href="#practice">學習方式</a><a href="#map">身體學習地圖</a><a href="#paths">三大探索入口</a></nav></div></section>
 ${section('path','01','身體，是回到自己的入口',`<div class="reading"><p>現代生活裡，我們習慣將注意力放在外在的目標、成果與標準上，卻有時忘記停下來，感受此刻的自己。</p><p>身體不只是需要被訓練、修正或改善的對象。它承載著感受、記憶、習慣與內在狀態。</p><p>透過身體覺察與動作探索，我們學習傾聽身體的訊息，重新建立與自己的連結，發展身體能力，並在表達與創造中走出自己的生命道路。</p></div>`)}
 ${section('soma','02','我們所說的身體',`<div class="reading"><p>Soma 指的是一個從內在被經驗著、被感受著、活著的身體。</p><p>我們不是站在外面觀看自己的身體，而是從身體裡感受、經驗與生活。身體不只是肌肉、骨骼或姿勢，也是我們感受世界、理解自己，並與生命互動的地方。</p></div>`)}
 ${section('practice','03','學習方式',`<div class="reading"><p>這裡不是追求標準答案的訓練場。每個人的身體都有自己的經驗、節奏與可能性。</p><p>我們透過感受、探索、移動與創造，陪伴每個人重新認識自己的身體。</p>${list(['覺察自己的狀態','理解身體的習慣','發展身體的能力','找到適合自己的表達方式'])}</div>`)}
 ${section('map','04','身體學習地圖',`<div class="reading"><p class="highlight">三大路徑 × 循環整合 × 持續深化</p><p>不同入口，同一個身體的旅程。三個探索入口在持續練習中彼此連結、循環深化，逐漸發展完整的身體經驗。</p><div class="image-placeholder">身體學習地圖視覺素材待確認</div></div>`)}
 ${section('paths','05','三大探索入口',courseCards)}`,
 courses:()=>`<section class="section"><div class="section-shell">${pageTitle('Courses','課程','每個人都有一條與身體相遇的道路。你可以從適合自己的入口開始，展開一段屬於自己的身體旅程。')}${courseCards}</div></section>`,
 'somatic-awareness':()=>seriesPage('Somatic Awareness','身心覺察','從身體感知開始，重新建立與自己的連結。',[['身體感知','提升對身體內在感受的敏銳度，學習傾聽身體正在傳遞的訊息。'],['動作覺察','透過動作練習，觀察自己的習慣模式與身體如何移動。'],['身心連結','從身體經驗出發，探索身體狀態、情緒與生命經驗之間的關係。'],['自我調整','在感受中找到適合自己的調整方式，建立身體與生活的平衡。']],['身心覺察入門工作坊','肌膜覺察與動作探索','脊椎感知與身體排列','慣性覺察與身體平衡','呼吸的身體、狀態與意識']),
 'soma-development':()=>seriesPage('Soma Development','肢體開發','探索身體能力，發展動作的可能性。',[['身體感知與放鬆','從脊椎活化、關節活動與基礎動作練習，重新感受身體的活動空間。'],['結構與穩定','透過核心、上下肢與全身連結練習，建立穩定、平衡與支撐。'],['流動與整合','透過流動性動作、節奏與舞蹈小品，探索身體的自然流動。']],[['脊椎活化與正位','入門全身舒展、脊椎多面向均衡伸展'],['核心連結與強化','核心多面向感知探索'],['腿後肌群連結與強化','核心與腿後肌群連動基礎'],['教具應用','身體力量 × 空間 × 流動整合課（肌膜球應用）']]),
 'dance-theatre':()=>seriesPage('Dance Theatre','舞蹈劇場','從身體經驗開始，探索表達與創造的可能。',[['身體表達','透過舞蹈作品、意象與身體經驗，探索動作所承載的生命品質與內在狀態。'],['創造探索','從身體經驗與動作元素出發，發展身體語彙與創作概念。'],['整合實踐','將身體覺察與動作能力轉化為更完整的表達與實踐。']],[['表演 Performance','生命儀式舞蹈；舞蹈作品尚待確認'],['創作 Creation','舞蹈編創基礎、劇場元素探索、個人的生命故事']]),
 'now-growing':()=>`<section class="section"><div class="section-shell">${pageTitle('Now Growing','正在發生','正在展開的身體旅程、活動與創作實踐。')}<nav class="quick-nav"><a href="#start">開始你的身體旅程</a><a href="#events">旅程與活動</a><a href="#past">Past Growing</a></nav></div></section>${section('start','01','開始你的身體旅程',`<div class="reading"><p>在這個空間裡，每個季節有不同的身體旅程展開。你可以依照自己的生命節奏，選擇適合自己的旅程。</p>${list(['春秋｜深度肢體開發旅程','全年｜一日身心覺察工作坊','夏季｜舞蹈劇場探索工作坊','年末｜作品與創造呈現'])}</div>`)}${section('events','02','旅程與活動',`<div class="grid two"><article class="card"><span class="en">2027 春季｜開放報名</span><h3>深度肢體開發旅程</h3><p>脊椎活化與正位 × 核心多面向感知探索<br>3月－6月</p><span class="placeholder">旅程詳細資料將於 CMS 階段建立</span></article><article class="card"><span class="en">全年｜開放報名</span><h3>一日身心覺察工作坊</h3><p>身體覺察、狀態與自我連結探索</p><span class="placeholder">旅程詳細資料將於 CMS 階段建立</span></article></div>`)}${section('past','03','歷年旅程紀錄',`<p class="reading">已完成的身體旅程、活動與創作紀錄，將於後續 Now Growing CMS 階段依同一筆旅程資料呈現。</p>`)}`,
 journal:()=>externalPage('Soma Journal','身體之書','從身體的探索裡，慢慢留下些什麼。','有一些身體裡的感受，會慢慢變成文字。這裡記錄喬馨對身體、生命與創作的觀察，也分享身體練習時的探索與發現。','閱讀身體之書','https://vocus.cc/salon/chiaohsin/room/bodymind','更多文章與身體探索內容，目前發表於方格子。'),
 video:()=>externalPage('Video','影音','身體 × 聲音 × 影像','身體練習、短片與創作影像，目前主要發表於 YouTube。','前往 YouTube 頻道','https://youtube.com/@shijoiuno',''),
 projects:()=>`<section class="section"><div class="section-shell">${pageTitle('Works','作品','從身體經驗開始，轉化為作品與表達。')}<div class="reading"><p>喬馨身體空間透過舞蹈劇場，將身體經驗、生命感受與創作探索，轉化為作品與實踐。</p><p>作品不只是動作的呈現，也是透過身體、意象與創作，探索生命經驗與表達方式的過程。</p></div></div></section>${section('works','Dance Theatre Works','舞蹈劇場作品',`<div class="reading"><p>作品將以卡片形式呈現，包含作品名稱、創作年份、作品簡介、作品圖片與 YouTube 影音連結。</p><p class="notice">目前尚未提供可公開呈現的作品資料；本區將於 Project CMS 階段依獨立作品資料建立。</p></div>`)}`,
 contact:()=>`<section class="section"><div class="section-shell">${pageTitle('Contact','聯絡')}<div class="reading"><p>如果你對課程或工作坊有任何問題，或是合作、講座、交流與其他相關邀請，歡迎與喬馨聯絡。</p><div class="topic"><span class="eyebrow">Email</span><h3>寫信給喬馨</h3><p><a class="button fill" href="mailto:shijoiuno@gmail.com">寫信給喬馨</a></p></div><div class="topic"><span class="eyebrow">LINE Official Account</span><h3>加入 LINE 官方帳號</h3><p class="placeholder">LINE Official Account：待建立</p></div></div></div></section>`
};
function seriesPage(en,zh,highlight,directions,courses){const cards=Array.isArray(courses[0])?courses.map(([t,d])=>`<article class="card"><h3>${t}</h3><p>${d}</p><span class="placeholder">課程詳細資料將於 Course CMS 階段建立</span></article>`).join(''):courses.map(t=>`<article class="card"><h3>${t}</h3><span class="placeholder">課程詳細資料將於 Course CMS 階段建立</span></article>`).join('');return `<section class="section"><div class="section-shell">${pageTitle(en,zh,highlight)}<nav class="quick-nav"><a href="#directions">探索方向</a><a href="#features">課程特色</a><a href="#audience">適合對象</a><a href="#course-list">課程列表</a></nav></div></section>${section('directions','01','探索方向',`<div class="grid">${directions.map(([t,d])=>`<article class="card"><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>`)}${section('features','02','課程特色',`<div class="reading"><p>課程從每個人的身體經驗出發，重視感受、探索、發展與整合，而非追求單一標準答案。</p></div>`)}${section('audience','03','適合對象',`<div class="reading"><p>適合想重新建立身體連結、發展身體能力，或透過身體進行表達與創作的人。可從當下的身體狀態開始。</p></div>`)}${section('course-list','04','課程列表',`<div class="grid two">${cards}</div><p class="notice">此頁的課程資料目前為已確認的靜態內容呈現；後續將由獨立 Course CMS 管理，不建立 Course Instance。</p>`)}`}
function externalPage(en,zh,headline,copy,label,url,note){return `<section class="section"><div class="section-shell">${pageTitle(en,zh)}<div class="external"><div><p class="highlight">${headline}</p><p>${copy}</p>${note?`<p>${note}</p>`:''}</div><a class="button fill" href="${url}" target="_blank" rel="noreferrer">${label}</a></div></div></section>`}
function setNavOpen(isOpen){const menu=document.querySelector('.nav-links'),button=document.querySelector('.nav-toggle');menu.classList.toggle('open',isOpen);button.setAttribute('aria-expanded',String(isOpen));button.setAttribute('aria-label',isOpen?'關閉導覽選單':'開啟導覽選單');button.querySelector('.menu-icon-open').toggleAttribute('hidden',isOpen);button.querySelector('.menu-icon-close').toggleAttribute('hidden',!isOpen)}
function render(){const route=(location.hash.match(/^#\/([^?]+)/)||[, 'home'])[1];const view=pages[route]||pages.home;document.querySelector('#main').innerHTML=view();document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));setNavOpen(false);window.scrollTo(0,0);document.title=`${route==='home'?'喬馨身體空間':(routes.find(x=>x[0]===route)||['','喬馨身體空間'])[1]}｜喬馨身體空間`}
document.querySelector('.nav-toggle').addEventListener('click',e=>setNavOpen(!document.querySelector('.nav-links').classList.contains('open')));
window.addEventListener('hashchange',render);render();

const confirmedFiles={about:'about-chiao-hsin-content-v0.1.md',home:'chiaohsin-soma-space-homepage-content-v1.0.md',journey:'chiaohsin-soma-space-soma-journey-content-v1.0.md',courses:'ourses-overview-content-v0.1.md','somatic-awareness':'somatic-awareness-page-content-v0.1.md','soma-development':'soma-development-page-content-v0.1.md','dance-theatre':'dance-theatre-page-content-v0.1.md','now-growing':'now-growing-content-v0.1.md',journal:'Soma Journal Content.md',video:'Video Content.md',projects:'projects-page-content-v0.2.md',contact:'Contact Content.md'};
const slug=t=>t.toLowerCase().replace(/[^\w\u4e00-\u9fff]+/g,'-').replace(/(^-|-$)/g,'');
function renderMarkdown(source){let html='',listOpen=false,skip=false;const meta=/^(Page Navigation|頁面快速導覽|Page Purpose|Design Notes|Future CMS Consideration|Future Expansion|Structure|Purpose|Hero|Section\s*\d+|第一區|第二區|第三區|第四區|第五區|第六區|功能定位|卡片範例|首頁設計原則|設計備註|後續擴充|Future)/i;const field=/^(英文小標|主標題|標題|內文|CTA|Button|Link|Highlight|功能|圖片說明|導覽項目|導覽設計原則|設計理念|目前課程|課程項目|延伸閱讀|Email|LINE Official Account)$/;for(const raw of source.split('\n')){const line=raw.trim();if(!line||line==='---'){if(listOpen){html+='</ul>';listOpen=false}continue}if(line.includes('然後下面各段標題改成一致'))continue;if(/^#/.test(line)){if(listOpen){html+='</ul>';listOpen=false}const title=line.replace(/^#+\s*/,'');skip=meta.test(title);if(skip||field.test(title))continue;html+=`<h2 id="${slug(title.replace(/^\d+\s*/,''))}">${title}</h2>`;continue}if(skip||field.test(line.replace(/[:：]$/,'')))continue;if(/^[-*] /.test(line)){if(!listOpen){html+='<ul>';listOpen=true}html+=`<li>${line.replace(/^[-*] /,'')}</li>`;continue}if(listOpen){html+='</ul>';listOpen=false}html+=`<p>${line.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')}</p>`}return html+(listOpen?'</ul>':'')}
async function renderConfirmedContent(){const route=(location.hash.match(/^#\/([^?]+)/)||[, 'home'])[1],file=confirmedFiles[route],source=window.SITE_CONTENT?.[file];if(!source)return;const root=document.querySelector('#main');root.innerHTML=`<section class="section"><div class="section-shell reading">${renderMarkdown(source)}${route==='contact'?'<p><a class="button fill" href="mailto:shijoiuno@gmail.com">寫信給喬馨</a></p>':''}</div></section>`;const headings=[...root.querySelectorAll('h2')].filter(h=>!/^Page Navigation|Section \d+|Design Notes|Future/.test(h.textContent));if(headings.length>2){const quick=document.createElement('nav');quick.className='quick-nav';quick.setAttribute('aria-label','頁面快速導覽');quick.innerHTML=headings.map(h=>`<a href="#${h.id}">${h.textContent.replace(/^\d+\s*/, '')}</a>`).join('');root.querySelector('.reading').prepend(quick)}}
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link||link.getAttribute('href').startsWith('#/'))return;const id=link.getAttribute('href').slice(1),target=document.getElementById(id);if(target){event.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}});
// Content is mapped into the page components; do not render source Markdown directly.
// window.addEventListener('hashchange',renderConfirmedContent);renderConfirmedContent();
